# Generated by Django 4.2.14 on 2024-08-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('director', models.CharField(max_length=100, verbose_name='Director')),
                ('year', models.DateField(max_length=100, verbose_name='Year')),
            ],
        ),
    ]
