# Generated by Django 4.2.14 on 2024-08-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_imdb_actors_imdb_description_imdb_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imdb',
            name='title',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
