# Generated by Django 4.2.14 on 2024-08-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_imdb_rank_alter_imdb_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdb',
            name='metascore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imdb',
            name='revenue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
